database:
  conn-url: postgres://postgres:oro@localhost:5432/postgres

tezos-client:
  url: https://api.tzkt.io/v1/operations/delegations
  timeout: 10s
  limit: 5

cron:
  spec: "*/1 * * * *"

api:
  port: ":8080"
