database:
  conn-url: postgres://postgres:oro@localhost:5432/tezosdb

tezos-client:
  url: https://api.tzkt.io/v1/operations/delegations
  timeout: 15s
  limit: 100

cron:
  spec: "*/1 * * * *"

api:
  default-limit: 10
  max-limit: 100
