basePath: /api/v1
definitions:
  handler.delegationJs:
    properties:
      amount:
        type: integer
      block:
        type: string
      delegator:
        type: string
      timestamp:
        type: string
    type: object
externalDocs:
  description: TezosAPI
  url: https://api.tzkt.io/#operation/Operations_GetDelegations
host: localhost:8080
info:
  contact:
    email: o.roux2@gmail.com
    name: API Support
  description: This is a simple service that will poll/return delegations on tezos
    protocol
  termsOfService: http://swagger.io/terms/
  title: Tezos Delegation Service
  version: "1.0"
paths:
  /xtz/delegations:
    get:
      consumes:
      - application/json
      description: Retrieve a list of delegations
      operationId: get-delegations
      parameters:
      - description: Limit the number of results (default is 10)
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Filter by year (optional)
        in: query
        name: year
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.delegationJs'
            type: array
      summary: Get delegations
swagger: "2.0"
